# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pgKDE_sph_vMF <- function(x, datax, h, cl, mu, nu) {
    .Call(`_pgKDEsphere_pgKDE_sph_vMF`, x, datax, h, cl, mu, nu)
}

KDE_sph_vMF <- function(x, datax, h, cl) {
    .Call(`_pgKDEsphere_KDE_sph_vMF`, x, datax, h, cl)
}

KDE <- function(x, datax, h, cl) {
    .Call(`_pgKDEsphere_KDE`, x, datax, h, cl)
}

